CREATE DATABASE IF NOT EXISTS norax_academy CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE norax_academy;

CREATE TABLE IF NOT EXISTS admins (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS students (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, phone VARCHAR(30), course VARCHAR(120), status ENUM('Active','Pending','Inactive') DEFAULT 'Active', joined_at DATE NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS courses (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(160) NOT NULL, description TEXT, price DECIMAL(12,2) DEFAULT 0, duration VARCHAR(80), image VARCHAR(255), status ENUM('Published','Draft') DEFAULT 'Published', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS instructors (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, specialty VARCHAR(120), bio TEXT, status ENUM('Active','On leave') DEFAULT 'Active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS enrollments (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, student_id INT UNSIGNED NOT NULL, course_id INT UNSIGNED NOT NULL, status ENUM('Active','Completed','Pending') DEFAULT 'Active', enrolled_at DATE NOT NULL, FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE, FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS payments (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, student_id INT UNSIGNED NOT NULL, amount DECIMAL(12,2) NOT NULL, method VARCHAR(40) DEFAULT 'Mobile Money', status ENUM('Paid','Pending','Failed') DEFAULT 'Paid', reference VARCHAR(80), paid_at DATE NOT NULL, FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS lessons (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, course_id INT UNSIGNED NOT NULL, title VARCHAR(180) NOT NULL, type ENUM('Video','Document','Link') DEFAULT 'Video', resource_url VARCHAR(255), duration VARCHAR(40), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS messages (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, student_id INT UNSIGNED NULL, subject VARCHAR(180) NOT NULL, body TEXT NOT NULL, status ENUM('Unread','Read') DEFAULT 'Unread', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS settings (id TINYINT UNSIGNED PRIMARY KEY, academy_name VARCHAR(160), email VARCHAR(190), phone VARCHAR(80), address VARCHAR(255), logo VARCHAR(255));

INSERT INTO courses (title, description, price, duration, status) SELECT 'Full-Stack Web Development', 'Build modern web products from interface to database.', 180000, '12 weeks', 'Published' WHERE NOT EXISTS (SELECT 1 FROM courses);
INSERT INTO courses (title, description, price, duration, status) SELECT 'UI/UX Product Design', 'Research, prototype and ship useful digital experiences.', 150000, '10 weeks', 'Published' WHERE (SELECT COUNT(*) FROM courses) = 1;
INSERT INTO settings (id, academy_name, email, phone, address) VALUES (1, 'NORAX ACADEMY', 'noraxacademy6@gmail.com', '+237688911917 / +237680092008', 'Yaoundé, Cameroon') ON DUPLICATE KEY UPDATE id=id;