<?php
declare(strict_types=1);
require_once __DIR__ . '/config/auth.php';
require_login();

$pdo = db();
$section = preg_replace('/[^a-z]/', '', (string) ($_GET['section'] ?? 'dashboard')) ?: 'dashboard';
$editId = (int) ($_GET['edit'] ?? 0);
$allowedSections = ['dashboard','students','courses','instructors','enrollments','payments','lessons','messages','reports','settings'];
if (!in_array($section, $allowedSections, true)) $section = 'dashboard';
$message = '';
$error = '';

try {
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        verify_csrf();
        $action = (string) ($_POST['action'] ?? '');
        if ($action === 'delete') {
            $table = (string) ($_POST['table'] ?? '');
            $safeTables = ['students','courses','instructors','enrollments','payments','lessons','messages'];
            if (in_array($table, $safeTables, true)) {
                $pdo->prepare("DELETE FROM {$table} WHERE id = ?")->execute([(int) $_POST['id']]);
                $message = 'Record deleted successfully.';
            }
        } elseif ($action === 'student') {
            $id = (int) ($_POST['id'] ?? 0); $name = trim((string) $_POST['name']); $email = trim((string) $_POST['email']);
            if (!$name || !filter_var($email, FILTER_VALIDATE_EMAIL)) throw new RuntimeException('Enter a valid student name and email.');
            if ($id) $pdo->prepare('UPDATE students SET name=?, email=?, phone=?, course=?, status=? WHERE id=?')->execute([$name,$email,trim((string) $_POST['phone']),trim((string) $_POST['course']),$_POST['status'],$id]);
            else $pdo->prepare('INSERT INTO students (name,email,phone,course,status,joined_at) VALUES (?,?,?,?,?,CURDATE())')->execute([$name,$email,trim((string) $_POST['phone']),trim((string) $_POST['course']),$_POST['status']]);
            $message = 'Student saved successfully.'; $section = 'students';
        } elseif ($action === 'course') {
            $id = (int) ($_POST['id'] ?? 0); $title = trim((string) $_POST['title']);
            if (!$title) throw new RuntimeException('A course title is required.');
            if ($id) $pdo->prepare('UPDATE courses SET title=?, description=?, price=?, duration=?, status=? WHERE id=?')->execute([$title,trim((string) $_POST['description']),(float) $_POST['price'],trim((string) $_POST['duration']),$_POST['status'],$id]);
            else $pdo->prepare('INSERT INTO courses (title,description,price,duration,status) VALUES (?,?,?,?,?)')->execute([$title,trim((string) $_POST['description']),(float) $_POST['price'],trim((string) $_POST['duration']),$_POST['status']]);
            $message = 'Course saved successfully.'; $section = 'courses';
        } elseif ($action === 'instructor') {
            $id = (int) ($_POST['id'] ?? 0); $name = trim((string) $_POST['name']); $email = trim((string) $_POST['email']);
            if (!$name || !filter_var($email, FILTER_VALIDATE_EMAIL)) throw new RuntimeException('Enter a valid instructor name and email.');
            if ($id) $pdo->prepare('UPDATE instructors SET name=?, email=?, specialty=?, bio=?, status=? WHERE id=?')->execute([$name,$email,trim((string) $_POST['specialty']),trim((string) $_POST['bio']),$_POST['status'],$id]);
            else $pdo->prepare('INSERT INTO instructors (name,email,specialty,bio,status) VALUES (?,?,?,?,?)')->execute([$name,$email,trim((string) $_POST['specialty']),trim((string) $_POST['bio']),$_POST['status']]);
            $message = 'Instructor saved successfully.'; $section = 'instructors';
        } elseif ($action === 'enrollment') {
            $pdo->prepare('INSERT INTO enrollments (student_id,course_id,status,enrolled_at) VALUES (?,?,?,CURDATE())')->execute([(int) $_POST['student_id'],(int) $_POST['course_id'],$_POST['status']]);
            $message = 'Enrollment recorded.'; $section = 'enrollments';
        } elseif ($action === 'payment') {
            $pdo->prepare('INSERT INTO payments (student_id,amount,method,status,reference,paid_at) VALUES (?,?,?,?,?,CURDATE())')->execute([(int) $_POST['student_id'],(float) $_POST['amount'],trim((string) $_POST['method']),$_POST['status'],trim((string) $_POST['reference'])]);
            $message = 'Payment recorded.'; $section = 'payments';
        } elseif ($action === 'lesson') {
            $pdo->prepare('INSERT INTO lessons (course_id,title,type,resource_url,duration) VALUES (?,?,?,?,?)')->execute([(int) $_POST['course_id'],trim((string) $_POST['title']),$_POST['type'],trim((string) $_POST['resource_url']),trim((string) $_POST['duration'])]);
            $message = 'Lesson added.'; $section = 'lessons';
        } elseif ($action === 'message') {
            $pdo->prepare('INSERT INTO messages (student_id,subject,body) VALUES (?,?,?)')->execute([($_POST['student_id'] ?? '') ?: null,trim((string) $_POST['subject']),trim((string) $_POST['body'])]);
            $message = 'Message sent.'; $section = 'messages';
        } elseif ($action === 'settings') {
            $pdo->prepare('UPDATE settings SET academy_name=?, email=?, phone=?, address=? WHERE id=1')->execute([trim((string) $_POST['academy_name']),trim((string) $_POST['email']),trim((string) $_POST['phone']),trim((string) $_POST['address'])]);
            $message = 'Settings updated.'; $section = 'settings';
        }
    }
} catch (Throwable $exception) { $error = $exception->getMessage(); }

function rows(PDO $pdo, string $sql, array $params = []): array { $statement = $pdo->prepare($sql); $statement->execute($params); return $statement->fetchAll(); }
function initials(string $name): string { $parts = preg_split('/\s+/', trim($name)); return strtoupper(substr($parts[0] ?? 'N',0,1) . substr($parts[1] ?? '',0,1)); }
function status_badge(string $status): string { $type = in_array($status, ['Active','Paid','Published','Completed','Read'], true) ? 'green' : (in_array($status, ['Pending','Draft','On leave'], true) ? 'amber' : 'red'); return '<span class="badge badge-' . $type . '">' . e($status) . '</span>'; }

$students = rows($pdo, 'SELECT * FROM students ORDER BY joined_at DESC');
$courses = rows($pdo, 'SELECT * FROM courses ORDER BY created_at DESC');
$instructors = rows($pdo, 'SELECT * FROM instructors ORDER BY created_at DESC');
$studentOptions = rows($pdo, 'SELECT id,name FROM students ORDER BY name');
$courseOptions = rows($pdo, 'SELECT id,title FROM courses ORDER BY title');
$recent = rows($pdo, 'SELECT name, email, joined_at FROM students ORDER BY joined_at DESC LIMIT 5');
$payments = rows($pdo, 'SELECT p.*, s.name FROM payments p JOIN students s ON s.id=p.student_id ORDER BY paid_at DESC LIMIT 30');
$enrollments = rows($pdo, 'SELECT e.*, s.name student_name, c.title course_title FROM enrollments e JOIN students s ON s.id=e.student_id JOIN courses c ON c.id=e.course_id ORDER BY enrolled_at DESC');
$lessons = rows($pdo, 'SELECT l.*, c.title course_title FROM lessons l JOIN courses c ON c.id=l.course_id ORDER BY l.created_at DESC');
$messages = rows($pdo, 'SELECT m.*, s.name student_name FROM messages m LEFT JOIN students s ON s.id=m.student_id ORDER BY m.created_at DESC');
$settings = $pdo->query('SELECT * FROM settings WHERE id=1')->fetch() ?: ['academy_name'=>'NORAX ACADEMY','email'=>'noraxacademy6@gmail.com','phone'=>'+237688911917 / +237680092008','address'=>'Yaoundé, Cameroon'];
$stats = ['students'=>(int)$pdo->query('SELECT COUNT(*) FROM students')->fetchColumn(),'courses'=>(int)$pdo->query('SELECT COUNT(*) FROM courses')->fetchColumn(),'instructors'=>(int)$pdo->query('SELECT COUNT(*) FROM instructors')->fetchColumn(),'revenue'=>(float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM payments WHERE status='Paid'")->fetchColumn()];
$editing = null;
if ($editId && in_array($section, ['students', 'courses', 'instructors'], true)) {
    $editing = $pdo->query('SELECT * FROM ' . $section . ' WHERE id=' . $editId)->fetch() ?: null;
}
$months = []; for ($i=5; $i>=0; $i--) { $date = new DateTime("first day of -{$i} months"); $months[] = ['label'=>$date->format('M'),'value'=>(int)$pdo->query("SELECT COUNT(*) FROM students WHERE MONTH(joined_at)={$date->format('n')} AND YEAR(joined_at)={$date->format('Y')}")->fetchColumn()]; }
$maxMonth = max(1, ...array_column($months, 'value'));
?>
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= e(ucfirst($section)) ?> | NORAX ACADEMY</title><link rel="stylesheet" href="assets/admin.css"></head>
<body><div class="app">
<aside class="sidebar"><a class="brand" href="index.php"><span class="brand-mark">N</span><span>NORAX <b>ACADEMY</b></span></a>
<nav><div class="nav-label">MAIN MENU</div><?php $nav=[['dashboard','▦','Dashboard'],['students','♙','Students'],['courses','▤','Courses'],['instructors','✦','Instructors'],['enrollments','↗','Enrollments'],['payments','₣','Payments'],['lessons','◫','Lessons'],['messages','✉','Messages']]; foreach($nav as $item): ?><a class="nav-link <?= $section===$item[0]?'active':'' ?>" href="?section=<?= $item[0] ?>"><span class="nav-icon"><?= $item[1] ?></span><?= $item[2] ?></a><?php endforeach; ?><div class="nav-label">INSIGHTS & SETTINGS</div><a class="nav-link <?= $section==='reports'?'active':'' ?>" href="?section=reports"><span class="nav-icon">▥</span>Reports</a><a class="nav-link <?= $section==='settings'?'active':'' ?>" href="?section=settings"><span class="nav-icon">⚙</span>Settings</a></nav>
<div class="sidebar-bottom"><div class="admin-mini"><span class="avatar"><?= e(initials((string)$_SESSION['admin_name'])) ?></span><span><?= e($_SESSION['admin_name']) ?></span></div><a class="logout-link" href="logout.php">↪ Sign out</a></div></aside>
<main class="main"><header class="topbar"><div class="top-actions"><button class="icon-button" data-menu aria-label="Open menu">☰</button><span class="breadcrumb">Workspace / <strong><?= e(ucfirst($section)) ?></strong></span></div><div class="top-actions"><a href="../index.html" title="View website">⌂</a><span class="avatar"><?= e(initials((string)$_SESSION['admin_name'])) ?></span></div></header>
<section class="content"><div class="heading-row"><div><h1><?= $section === 'dashboard' ? 'Good morning, ' . e(explode(' ', trim((string)$_SESSION['admin_name']))[0]) . '.' : e(ucfirst($section)) ?></h1><p class="subtitle"><?= $section === 'dashboard' ? 'Here is what is happening at NORAX ACADEMY today.' : 'Manage your academy workspace from one place.' ?></p></div><?php if(in_array($section,['students','courses','instructors','enrollments','payments','lessons','messages'],true)): ?><a class="button button-primary" href="#add-form">+ Add <?= rtrim(ucfirst($section),'s') ?></a><?php endif; ?></div>
<?php if($message): ?><div class="alert alert-success"><?= e($message) ?></div><?php endif; ?><?php if($error): ?><div class="alert alert-error"><?= e($error) ?></div><?php endif; ?>
<?php if($section==='dashboard'): ?>
<div class="metrics"><div class="metric"><div class="metric-top">Total students <span class="metric-icon">♙</span></div><div class="metric-value"><?= number_format($stats['students']) ?></div><div class="metric-note">Active academy learners</div></div><div class="metric"><div class="metric-top">Active courses <span class="metric-icon">▤</span></div><div class="metric-value"><?= number_format($stats['courses']) ?></div><div class="metric-note">Published programs</div></div><div class="metric"><div class="metric-top">Instructors <span class="metric-icon">✦</span></div><div class="metric-value"><?= number_format($stats['instructors']) ?></div><div class="metric-note">Teaching team</div></div><div class="metric"><div class="metric-top">Revenue <span class="metric-icon">₣</span></div><div class="metric-value"><?= number_format($stats['revenue']) ?><small> XAF</small></div><div class="metric-note">Paid transactions</div></div></div>
<div class="dashboard-grid"><div><div class="panel"><div class="panel-head"><h2>Registration overview</h2><span class="muted">Last 6 months</span></div><div class="panel-body"><div class="bars"><?php foreach($months as $month): ?><div class="bar-wrap"><div class="bar <?= $month['label']===date('M')?'active':'' ?>" style="height:<?= max(8,($month['value']/$maxMonth)*100) ?>%" title="<?= $month['value'] ?> registrations"></div><span class="bar-label"><?= e($month['label']) ?></span></div><?php endforeach; ?></div></div></div><div class="panel"><div class="panel-head"><h2>Recent registrations</h2><a href="?section=students">View all →</a></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Course</th><th>Date joined</th><th>Status</th></tr></thead><tbody><?php foreach(array_slice($students,0,5) as $student): ?><tr><td><div class="person"><span class="avatar"><?= e(initials($student['name'])) ?></span><?= e($student['name']) ?></div></td><td><?= e($student['course'] ?: 'Not assigned') ?></td><td><?= e(date('d M Y',strtotime($student['joined_at']))) ?></td><td><?= status_badge($student['status']) ?></td></tr><?php endforeach; if(!$students): ?><tr><td colspan="4" class="muted">No registrations yet.</td></tr><?php endif; ?></tbody></table></div></div></div>
<div><div class="panel"><div class="panel-head"><h2>Course performance</h2><a href="?section=courses">Manage →</a></div><div class="panel-body"><?php foreach($courses as $course): $count=(int)$pdo->query('SELECT COUNT(*) FROM enrollments WHERE course_id='.(int)$course['id'])->fetchColumn(); ?><div class="progress-row"><div class="progress-label"><b><?= e($course['title']) ?></b><span><?= $count ?> enrolled</span></div><div class="progress"><i style="width:<?= min(100,max(8,$count*12)) ?>%"></i></div></div><?php endforeach; if(!$courses): ?><p class="muted">Add a course to see performance.</p><?php endif; ?></div></div><div class="panel"><div class="panel-head"><h2>Latest activity</h2></div><div class="panel-body"><?php foreach($recent as $item): ?><div class="activity"><span class="avatar"><?= e(initials($item['name'])) ?></span><p><b><?= e($item['name']) ?></b> registered for a course<br><small><?= e(date('d M Y',strtotime($item['joined_at']))) ?></small></p></div><?php endforeach; if(!$recent): ?><p class="muted">No activity yet.</p><?php endif; ?></div></div></div></div>
<?php elseif($section==='students'): ?><div class="panel"><div class="filters"><input class="search" data-filter=".data-row" placeholder="Search students..."><span class="muted"><?= count($students) ?> students</span></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Email / phone</th><th>Course</th><th>Joined</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($students as $row): ?><tr class="data-row"><td><div class="person"><span class="avatar"><?= e(initials($row['name'])) ?></span><?= e($row['name']) ?></div></td><td><?= e($row['email']) ?><br><small class="muted"><?= e($row['phone']) ?></small></td><td><?= e($row['course'] ?: 'Not assigned') ?></td><td><?= e(date('d M Y',strtotime($row['joined_at']))) ?></td><td><?= status_badge($row['status']) ?></td><td><a class="button button-quiet button-small" href="?section=students&edit=<?= $row['id'] ?>#add-form">Edit</a> <form method="post" style="display:inline"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="table" value="students"><input type="hidden" name="id" value="<?= $row['id'] ?>"><button class="button button-danger button-small" data-confirm="Delete this student?">Delete</button></form></td></tr><?php endforeach; if(!$students): ?><tr><td colspan="6" class="muted">No students yet.</td></tr><?php endif; ?></tbody></table></div></div><div class="panel" id="add-form"><div class="panel-head"><h2><?= $editing ? 'Edit student' : 'Add student' ?></h2></div><div class="panel-body"><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="student"><input type="hidden" name="id" value="<?= (int)($editing['id'] ?? 0) ?>"><div class="form-grid"><div class="form-group"><label>Full name<input name="name" required value="<?= e($editing['name'] ?? '') ?>"></label></div><div class="form-group"><label>Email<input type="email" name="email" required value="<?= e($editing['email'] ?? '') ?>"></label></div><div class="form-group"><label>Phone<input name="phone" value="<?= e($editing['phone'] ?? '') ?>"></label></div><div class="form-group"><label>Course<input name="course" value="<?= e($editing['course'] ?? '') ?>"></label></div><div class="form-group"><label>Status<select name="status"><option <?= ($editing['status'] ?? '')==='Active'?'selected':'' ?>>Active</option><option <?= ($editing['status'] ?? '')==='Pending'?'selected':'' ?>>Pending</option><option <?= ($editing['status'] ?? '')==='Inactive'?'selected':'' ?>>Inactive</option></select></label></div></div><div class="form-actions"><button class="button button-primary">Save student</button></div></form></div></div>
<?php elseif($section==='courses'): ?><div class="panel"><div class="filters"><input class="search" data-filter=".data-row" placeholder="Search courses..."><span class="muted"><?= count($courses) ?> courses</span></div><div class="table-wrap"><table><thead><tr><th>Course</th><th>Duration</th><th>Price</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($courses as $row): ?><tr class="data-row"><td><b><?= e($row['title']) ?></b><br><small class="muted"><?= e(mb_strimwidth((string)$row['description'],0,70,'...')) ?></small></td><td><?= e($row['duration']) ?></td><td><?= number_format((float)$row['price']) ?> XAF</td><td><?= status_badge($row['status']) ?></td><td><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="table" value="courses"><input type="hidden" name="id" value="<?= $row['id'] ?>"><button class="button button-danger button-small" data-confirm="Delete this course and its lessons?">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div></div><div class="panel" id="add-form"><div class="panel-head"><h2>Create course</h2></div><div class="panel-body"><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="course"><div class="form-grid"><div class="form-group"><label>Course title<input name="title" required></label></div><div class="form-group"><label>Duration<input name="duration" placeholder="e.g. 12 weeks"></label></div><div class="form-group"><label>Price (XAF)<input type="number" name="price" min="0" required></label></div><div class="form-group"><label>Status<select name="status"><option>Published</option><option>Draft</option></select></label></div><div class="form-group full"><label>Description<textarea name="description" required></textarea></label></div></div><div class="form-actions"><button class="button button-primary">Save course</button></div></form></div></div>
<?php elseif($section==='instructors'): ?><div class="panel"><div class="table-wrap"><table><thead><tr><th>Instructor</th><th>Specialty</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($instructors as $row): ?><tr><td><div class="person"><span class="avatar"><?= e(initials($row['name'])) ?></span><?= e($row['name']) ?></div></td><td><?= e($row['specialty']) ?></td><td><?= e($row['email']) ?></td><td><?= status_badge($row['status']) ?></td><td><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="table" value="instructors"><input type="hidden" name="id" value="<?= $row['id'] ?>"><button class="button button-danger button-small" data-confirm="Delete this instructor?">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div></div><div class="panel" id="add-form"><div class="panel-head"><h2>Add instructor</h2></div><div class="panel-body"><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="instructor"><div class="form-grid"><div class="form-group"><label>Full name<input name="name" required></label></div><div class="form-group"><label>Email<input type="email" name="email" required></label></div><div class="form-group"><label>Specialty<input name="specialty"></label></div><div class="form-group"><label>Status<select name="status"><option>Active</option><option>On leave</option></select></label></div><div class="form-group full"><label>Bio<textarea name="bio"></textarea></label></div></div><div class="form-actions"><button class="button button-primary">Save instructor</button></div></form></div></div>
<?php elseif($section==='enrollments'): ?><div class="panel"><div class="panel-head"><h2>Course registrations</h2></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Course</th><th>Enrolled</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($enrollments as $row): ?><tr><td><?= e($row['student_name']) ?></td><td><?= e($row['course_title']) ?></td><td><?= e($row['enrolled_at']) ?></td><td><?= status_badge($row['status']) ?></td><td><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="table" value="enrollments"><input type="hidden" name="id" value="<?= $row['id'] ?>"><button class="button button-danger button-small" data-confirm="Delete this enrollment?">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div></div><div class="panel" id="add-form"><div class="panel-head"><h2>Record enrollment</h2></div><div class="panel-body"><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="enrollment"><div class="form-grid"><div class="form-group"><label>Student<select name="student_id" required><?php foreach($studentOptions as $item): ?><option value="<?= $item['id'] ?>"><?= e($item['name']) ?></option><?php endforeach; ?></select></label></div><div class="form-group"><label>Course<select name="course_id" required><?php foreach($courseOptions as $item): ?><option value="<?= $item['id'] ?>"><?= e($item['title']) ?></option><?php endforeach; ?></select></label></div><div class="form-group"><label>Status<select name="status"><option>Active</option><option>Pending</option><option>Completed</option></select></label></div></div><div class="form-actions"><button class="button button-primary">Record enrollment</button></div></form></div></div>
<?php elseif($section==='payments'): ?><div class="panel"><div class="panel-head"><h2>Payment transactions</h2><span class="muted">All amounts in XAF</span></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Amount</th><th>Method</th><th>Reference</th><th>Date</th><th>Status</th></tr></thead><tbody><?php foreach($payments as $row): ?><tr><td><?= e($row['name']) ?></td><td><b><?= number_format((float)$row['amount']) ?></b> XAF</td><td><?= e($row['method']) ?></td><td><?= e($row['reference']) ?></td><td><?= e($row['paid_at']) ?></td><td><?= status_badge($row['status']) ?></td></tr><?php endforeach; ?></tbody></table></div></div><div class="panel" id="add-form"><div class="panel-head"><h2>Record payment</h2></div><div class="panel-body"><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="payment"><div class="form-grid"><div class="form-group"><label>Student<select name="student_id" required><?php foreach($studentOptions as $item): ?><option value="<?= $item['id'] ?>"><?= e($item['name']) ?></option><?php endforeach; ?></select></label></div><div class="form-group"><label>Amount (XAF)<input type="number" name="amount" min="1" required></label></div><div class="form-group"><label>Payment method<input name="method" value="Mobile Money"></label></div><div class="form-group"><label>Reference<input name="reference"></label></div><div class="form-group"><label>Status<select name="status"><option>Paid</option><option>Pending</option><option>Failed</option></select></label></div></div><div class="form-actions"><button class="button button-primary">Record payment</button></div></form></div></div>
<?php elseif($section==='lessons'): ?><div class="panel"><div class="panel-head"><h2>Course materials</h2></div><div class="table-wrap"><table><thead><tr><th>Lesson</th><th>Course</th><th>Type</th><th>Duration</th><th>Resource</th><th>Action</th></tr></thead><tbody><?php foreach($lessons as $row): ?><tr><td><?= e($row['title']) ?></td><td><?= e($row['course_title']) ?></td><td><?= status_badge($row['type']) ?></td><td><?= e($row['duration']) ?></td><td><?= $row['resource_url'] ? '<a class="button button-quiet button-small" target="_blank" href="'.e($row['resource_url']).'">Open</a>' : '<span class="muted">Not set</span>' ?></td><td><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="table" value="lessons"><input type="hidden" name="id" value="<?= $row['id'] ?>"><button class="button button-danger button-small" data-confirm="Delete this lesson?">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div></div><div class="panel" id="add-form"><div class="panel-head"><h2>Add lesson or resource</h2></div><div class="panel-body"><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="lesson"><div class="form-grid"><div class="form-group"><label>Course<select name="course_id" required><?php foreach($courseOptions as $item): ?><option value="<?= $item['id'] ?>"><?= e($item['title']) ?></option><?php endforeach; ?></select></label></div><div class="form-group"><label>Lesson title<input name="title" required></label></div><div class="form-group"><label>Type<select name="type"><option>Video</option><option>Document</option><option>Link</option></select></label></div><div class="form-group"><label>Duration<input name="duration" placeholder="e.g. 24 min"></label></div><div class="form-group full"><label>Resource URL<input type="url" name="resource_url" placeholder="https://..."></label></div></div><div class="form-actions"><button class="button button-primary">Add lesson</button></div></form></div></div>
<?php elseif($section==='messages'): ?><div class="panel"><div class="panel-head"><h2>Messages</h2></div><div class="table-wrap"><table><thead><tr><th>Recipient</th><th>Subject</th><th>Message</th><th>Sent</th><th>Status</th></tr></thead><tbody><?php foreach($messages as $row): ?><tr><td><?= e($row['student_name'] ?: 'All students') ?></td><td><b><?= e($row['subject']) ?></b></td><td><?= e(mb_strimwidth($row['body'],0,80,'...')) ?></td><td><?= e(date('d M Y',strtotime($row['created_at']))) ?></td><td><?= status_badge($row['status']) ?></td></tr><?php endforeach; ?></tbody></table></div></div><div class="panel" id="add-form"><div class="panel-head"><h2>Compose message</h2></div><div class="panel-body"><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="message"><div class="form-grid"><div class="form-group"><label>Recipient<select name="student_id"><option value="">All students</option><?php foreach($studentOptions as $item): ?><option value="<?= $item['id'] ?>"><?= e($item['name']) ?></option><?php endforeach; ?></select></label></div><div class="form-group"><label>Subject<input name="subject" required></label></div><div class="form-group full"><label>Message<textarea name="body" required></textarea></label></div></div><div class="form-actions"><button class="button button-primary">Send message</button></div></form></div></div>
<?php elseif($section==='reports'): ?><div class="metrics"><div class="metric"><div class="metric-top">Students</div><div class="metric-value"><?= number_format($stats['students']) ?></div><div class="metric-note">Total registered</div></div><div class="metric"><div class="metric-top">Enrollments</div><div class="metric-value"><?= number_format(count($enrollments)) ?></div><div class="metric-note">All course registrations</div></div><div class="metric"><div class="metric-top">Paid revenue</div><div class="metric-value"><?= number_format($stats['revenue']) ?><small> XAF</small></div><div class="metric-note">Confirmed payments</div></div><div class="metric"><div class="metric-top">Pending fees</div><div class="metric-value"><?= number_format((float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM payments WHERE status='Pending'")->fetchColumn()) ?><small> XAF</small></div><div class="metric-note">Awaiting payment</div></div></div><div class="panel"><div class="panel-head"><h2>Revenue report</h2><button class="button button-quiet button-small" onclick="window.print()">Print report</button></div><div class="panel-body"><p class="muted">This report reflects live records in the academy database. Use your browser print dialog to save a PDF.</p><div class="bars"><?php $revenueMax=max(1,(float)$stats['revenue']); foreach(array_slice($payments,0,6) as $payment): ?><div class="bar-wrap"><div class="bar active" style="height:<?= max(8,((float)$payment['amount']/$revenueMax)*100) ?>%" title="<?= number_format((float)$payment['amount']) ?> XAF"></div><span class="bar-label"><?= e(date('d M',strtotime($payment['paid_at']))) ?></span></div><?php endforeach; ?></div></div></div>
<?php elseif($section==='settings'): ?><div class="panel"><div class="panel-head"><h2>Academy information</h2></div><div class="panel-body"><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="settings"><div class="form-grid"><div class="form-group"><label>Academy name<input name="academy_name" value="<?= e($settings['academy_name']) ?>" required></label></div><div class="form-group"><label>Contact email<input type="email" name="email" value="<?= e($settings['email']) ?>" required></label></div><div class="form-group"><label>Phone numbers<input name="phone" value="<?= e($settings['phone']) ?>" required></label></div><div class="form-group"><label>Address<input name="address" value="<?= e($settings['address']) ?>"></label></div></div><div class="form-actions"><button class="button button-primary">Save settings</button></div></form></div></div><?php endif; ?>
</section></main></div><script src="assets/admin.js"></script></body></html>